# Generated by Django 3.1.5 on 2021-02-02 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210201_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsrequest',
            name='part',
        ),
        migrations.RemoveField(
            model_name='partsrequest',
            name='user',
        ),
        migrations.RenameField(
            model_name='bilingcontract',
            old_name='billingcontracts',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='enquiries',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='enquiries',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='inventry',
            old_name='date',
            new_name='tag_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_Phone',
            new_name='landline_phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='landine_number',
            new_name='mobile_Phone',
        ),
        migrations.RenameField(
            model_name='shippingcontract',
            old_name='shippingcontracts',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppliers',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='enquiries',
            name='part_request',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 2, 8, 16, 13, 990430, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='zip_code',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_customer', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person_customer', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventry'),
        ),
        migrations.AddField(
            model_name='inventry',
            name='alt_part_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventry',
            name='part_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='enquiries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.enquiries'),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.country'),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='certification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='condition',
            field=models.CharField(blank=True, choices=[('NE', 'ne'), ('NS', 'ns'), ('SV', 'sv'), ('AR', 'ar'), ('FN', 'fn'), ('US', 'us'), ('RP', 'rp')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='hazmat',
            field=models.CharField(blank=True, choices=[('YES', 'yeas'), ('No', 'no')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='hot_sale_item',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('No', 'no')], max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.DeleteModel(
            name='PartsRequest',
        ),
    ]
