# Generated by Django 3.1.5 on 2021-02-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210202_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilingcontract',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shippingcontract',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelTable(
            name='bilingcontract',
            table='oas_billing_contract',
        ),
        migrations.AlterModelTable(
            name='category',
            table='oas_category',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='oas_contract',
        ),
        migrations.AlterModelTable(
            name='country',
            table='oas_country',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='oas_customer',
        ),
        migrations.AlterModelTable(
            name='enquiries',
            table='oas_enquiries_contract',
        ),
        migrations.AlterModelTable(
            name='inventry',
            table='oas_inventry',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='oas_manufacturer',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='oas_profile',
        ),
        migrations.AlterModelTable(
            name='shippingcontract',
            table='oas_shipping_contract',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='oas_supplier',
        ),
    ]
