# Generated by Django 3.1.5 on 2021-02-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0004_auto_20210202_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('contact_person', models.CharField(blank=True, max_length=191, null=True)),
                ('email', models.CharField(max_length=191)),
                ('bill_address_one', models.TextField(blank=True, null=True)),
                ('bill_address_two', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.country')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_inventory.contact_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'oas_contact',
            },
        ),
        migrations.RenameModel(
            old_name='Inventry',
            new_name='Inventory',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='shippingcontract',
            name='contract_ptr',
        ),
        migrations.AlterModelTable(
            name='enquiries',
            table='oas_enquiries',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='oas_inventory',
        ),
        migrations.CreateModel(
            name='BillingContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.contact')),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'oas_billing_contact',
            },
            bases=('inventory.contact',),
        ),
        migrations.CreateModel(
            name='ShippingContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.contact')),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'oas_shipping_contact',
            },
            bases=('inventory.contact',),
        ),
        migrations.DeleteModel(
            name='BilingContract',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ShippingContract',
        ),
    ]
