# Generated by Django 3.1.5 on 2021-02-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210203_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
    ]
